### ISSUE TITLE
Error while running the workflow

### ISSUE THREAD

**Issue by thammegowda** [chrismattmann/bigtranslate#9]
@chrismattmann 
I updated workflow configuration with legacy flags as per your suggestion from drat ( https://github.com/chrismattmann/drat/blob/master/workflow/src/main/resources/bin/wmgr#L87-88)

Now a new issue started showing up. Looks like the workflow manager has trouble picking the input tsv file.

I tried giving the relative path and absolute path, but I got the same exception in both the cases.
## Command

<pre>
 $ ./workflow/bin/wmgr-client --url http://localhost:9001 --operation --dynWorkflow \
    --taskIds urn:bigtranslate:TsvToJson_Task \
    --metaData --key Filename $PWD/computrabajo-ar-20121106.tsv 
Started dynamic workflow with id '1d52642d-2867-11e6-b469-4130e4106b15'
</pre>

The complete activity is recorded for reference :
  http://showterm.io/f2d4aad1b1ab813c43a46#230
## Exception:

<pre>
SEVERE: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
Jun 01, 2016 7:09:34 PM org.apache.oodt.cas.pge.PGETaskInstance run
SEVERE: PGETask FAILED!!! : Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM EmploymentJobAggregatesTsv WHERE Filename = 'computrabajo-ar-20121106.tsv'}
java.io.IOException: Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM EmploymentJobAggregatesTsv WHERE Filename = 'computrabajo-ar-20121106.tsv'}
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:68)
    at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:217)
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:109)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:573)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:324)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.oodt.cas.pge.exceptions.PGEException: Failed to parse value: SQL(FORMAT='$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM EmploymentJobAggregatesTsv WHERE Filename = 'computrabajo-ar-20121106.tsv'}
    at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:461)
    at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:439)
    at org.apache.oodt.cas.pge.util.XmlHelper.getMetadataValues(XmlHelper.java:204)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.loadCustomMetadata(XmlFilePgeConfigBuilder.java:146)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.loadConfigFile(XmlFilePgeConfigBuilder.java:101)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:64)
    ... 6 more
Caused by: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: org.apache.xmlrpc.XmlRpcException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
    at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:997)
    at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:451)
    ... 11 more
Caused by: org.apache.xmlrpc.XmlRpcException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeException(XmlRpcClientResponseProcessor.java:104)
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeResponse(XmlRpcClientResponseProcessor.java:71)
    at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:73)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
    at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:991)
    ... 12 more

</pre>

I couldnt debug this myslelf, Please help me resolve this issue?

**Comment by chrismattmann** [comment]
will investigate this @thammegowda

**Comment by chrismattmann** [comment]
@thammegowda does your latest PR fix this?

**Comment by thammegowda** [comment]
@chrismattmann Yes, the latest PR fixed this

**Comment by chrismattmann** [comment]
resolving
